name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "286c101b-2bbd-4d64-99b7-45c6a8098348"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "f590956714f642088d1546b15671d5f8"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
